### ISSUE TITLE
allow gzipped reference

### ISSUE THREAD

**Issue by macmanes** [Blahah/transrate#163]
This fails, because the references is gzipped:
Seems like we should be able to input a gzipped reference, no?

```
transrate --assembly ../trinity_1M/trinity_1M.P2.raw.Trinity.fasta --left ../reads/SRR797058_1.fastq.gz --right ../reads/SRR797058_2.fastq.gz --reference ../genome/Mus_musculus.GRCm38.dna.chromosome.1.fa.gz --threads 10
```

error
```
/home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/ruby/2.2.0/gems/bio-1.5.0/lib/bio/db/fasta/defline.rb:207:in `add_defline': undefined method `join' for nil:NilClass (NoMethodError)
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/ruby/2.2.0/gems/bio-1.5.0/lib/bio/db/fasta/defline.rb:189:in `block in initialize'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/ruby/2.2.0/gems/bio-1.5.0/lib/bio/db/fasta/defline.rb:188:in `each'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/ruby/2.2.0/gems/bio-1.5.0/lib/bio/db/fasta/defline.rb:188:in `initialize'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/ruby/2.2.0/gems/bio-1.5.0/lib/bio/db/fasta.rb:245:in `new'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/ruby/2.2.0/gems/bio-1.5.0/lib/bio/db/fasta.rb:245:in `identifiers'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/ruby/2.2.0/gems/bio-1.5.0/lib/bio/db/fasta.rb:254:in `entry_id'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/contig.rb:27:in `initialize'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/assembly.rb:56:in `new'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/assembly.rb:56:in `block in initialize'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/ruby/2.2.0/gems/bio-1.5.0/lib/bio/io/flatfile.rb:336:in `each_entry'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/assembly.rb:50:in `initialize'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/cmdline.rb:27:in `new'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/cmdline.rb:27:in `run'
	from /home/ubuntu/transrate-1.0.1-linux-x86_64/lib/app/bin/transrate:23:in `<main>'
```

**Comment by Blahah** [comment]
Sounds like a sensible thing to support - +1

**Comment by Blahah** [comment]
from #167 - also show a sensible error message when we can't parse the assembly
