### ISSUE TITLE
undefined method `length' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ljcohen** [blahah/transrate#182]
I received the following error on Ubuntu 14.04, but the assemblies.csv results were output anyway. Is this something to be concerned about?
```
[ INFO] 2016-02-03 21:56:27 : Calculating contig metrics...
/bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/assembly.rb:181:in `basic_bin_stats': undefined method `length' for nil:NilClass (NoMethodError)
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/assembly.rb:100:in `basic_stats'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/assembly.rb:77:in `run'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/transrater.rb:80:in `assembly_metrics'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/cmdline.rb:443:in `contig_metrics'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/cmdline.rb:379:in `block in analyse_assembly'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/cmdline.rb:376:in `chdir'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/cmdline.rb:376:in `analyse_assembly'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/cmdline.rb:38:in `block (2 levels) in run'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/cmdline.rb:37:in `zip'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/cmdline.rb:37:in `block in run'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/cmdline.rb:32:in `chdir'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/lib/transrate/cmdline.rb:32:in `run'
        from /bin/transrate-1.0.1-linux-x86_64/lib/app/bin/transrate:23:in `<main>'
Dictyocha_speculum_SRR1300447
```

**Comment by Blahah** [comment]
@ljcohen apologies that I missed this issue. It looks like for some reason you have a contig with no sequence - or possibly your FASTA file failed to parse. If you're still seeing this error I can give live help in the gitter chat room https://gitter.im/Blahah/transrate
