### ISSUE TITLE
After installing transrate  via ruby showing syntex errror

### ISSUE THREAD

**Issue by hackerzone85** [blahah/transrate#205]
```
blab:~$ transrate --help
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/transrate-1.0.1/lib/transrate/transrater.rb:23: syntax error, unexpected tLABEL (SyntaxError)
    def initialize(assembly, reference, threads: 1)
                                                ^
/var/lib/gems/1.9.1/gems/transrate-1.0.1/lib/transrate/transrater.rb:119: syntax error, unexpected keyword_end, expecting $end
end # Transrate
   ^
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/transrate-1.0.1/lib/transrate.rb:30:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/transrate-1.0.1/bin/transrate:2:in `<top (required)>'
	from /usr/local/bin/transrate:23:in `load'
	from /usr/local/bin/transrate:23:in `<main>'
````

**Comment by blahah** [comment]
transrate is only compatible with ruby v2 and above as specified in the [installation documentation](http://hibberdlab.com/transrate/installation.html#advanced-installation)

We provide some instructions for upgrading ruby on that page too :)
