### ISSUE TITLE
makeblastdb issues

### ISSUE THREAD

**Issue by genizamt** [blahah/transrate#207]
command run:
transrate --threads 8  --assembly transcripts_CCDR_T0-output-v2-cdhitest --reference Oryza_sativa.IRGSP-1.0.cdna.all.fa

contig metrics are generated, but errors out when generating comparative metrics:

/local/cluster/transrate/lib/app/bin/transrate:13:in `raise': BLAST Error creating database: (RuntimeError)

USAGE
  makeblastdb [-h] [-help] [-in input_file] [-input_type type]
    -dbtype molecule_type [-title database_title] [-parse_seqids]
    [-hash_index] [-mask_data mask_data_files] [-mask_id mask_algo_ids]
    [-mask_desc mask_algo_descriptions] [-gi_mask]
    [-gi_mask_name gi_based_mask_names] [-out database_name]
    [-max_file_sz number_of_bytes] [-logfile File_Name] [-taxid TaxID]
    [-taxid_map TaxIDMapFile] [-version]

DESCRIPTION
   Application to create BLAST databases, version 2.2.31+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error: Too many positional arguments (1), the offending value: ./
	from /local/cluster/transrate/lib/app/ruby/2.2.0/gems/crb-blast-0.6.6/lib/crb-blast/crb-blast.rb:119:in `makedb'
	from /local/cluster/transrate/lib/app/ruby/2.2.0/gems/crb-blast-0.6.6/lib/crb-blast/crb-blast.rb:514:in `run'
	from /local/cluster/transrate/lib/app/lib/transrate/comparative_metrics.rb:154:in `run_crb_blast'
	from /local/cluster/transrate/lib/app/lib/transrate/comparative_metrics.rb:23:in `run'
	from /local/cluster/transrate/lib/app/lib/transrate/transrater.rb:115:in `comparative_metrics'
	from /local/cluster/transrate/lib/app/lib/transrate/cmdline.rb:528:in `comparative_metrics'
	from /local/cluster/transrate/lib/app/lib/transrate/cmdline.rb:405:in `block in analyse_assembly'
	from /local/cluster/transrate/lib/app/lib/transrate/cmdline.rb:400:in `chdir'
	from /local/cluster/transrate/lib/app/lib/transrate/cmdline.rb:400:in `analyse_assembly'
	from /local/cluster/transrate/lib/app/lib/transrate/cmdline.rb:38:in `block (2 levels) in run'
	from /local/cluster/transrate/lib/app/lib/transrate/cmdline.rb:37:in `zip'
	from /local/cluster/transrate/lib/app/lib/transrate/cmdline.rb:37:in `block in run'
	from /local/cluster/transrate/lib/app/lib/transrate/cmdline.rb:32:in `chdir'
	from /local/cluster/transrate/lib/app/lib/transrate/cmdline.rb:32:in `run'
	from /local/cluster/transrate/lib/app/bin/transrate:23:in `<main>'

**Comment by blahah** [comment]
how did you install transrate? It looks to me like transrate is trying to use a version of blast that you already have installed (`2.3.31`), rather than the one it needs (`2.2.29`)

You can either try `transrate --install-deps` or try the binary distribution of transrate from http://hibberdlab.com/transrate/installation.html

**Comment by genizamt** [comment]
Thanks for the reply,

I work on a linux cluster -common tools like BLAST get updated 
regularly. a local copy of transrate was installed by downloading the 
linux binary, unpacking and adding the directory to the path.

$transrate --install-deps ref
Checking dependencies
All dependencies installed

Ill could try to install a local copy of 2.2.29, but a similar user had 
the same makeblastdb problem. They mentioned a workaround, but no final 
resolution was provided.
https://groups.google.com/forum/#!topic/transrate-users/7QZ4EXyMFLY

Is there a way to bypass the makeblastdb step and jump directly into the 
blast? standalone, the makeblastdb command works and generates the 
appropriate *nin, *nsq, and *nih. I could just move those to the 
appropriate transrate directory.

**Comment by blahah** [comment]
Thanks for reporting this - it's actually a bug with how we load the dependencies in a rare case.

Do you have access to edit the `/local/cluster/transrate/` file? Below I describe the fix depending on whether or not you can edit it:

### If you can edit the file

replace the line:

```bash
export PATH=$SELFDIR/bin:$PATH
```

with:

```bash
export PATH=$SELFDIR/bin:$SELFDIR/lib/app/ruby/2.2.0/bin:$PATH
```

this will fix it for everyone who's using it

### If you can't edit the file

when you run transrate, you'll have to run it like this:

```bash
PATH=/local/cluster/transrate/lib/app/ruby/2.2.0/bin:$PATH transrate
```

and put whatever arguments you wanted afterwards, e.g. in your example:

```bash
transrate --threads 8 --assembly transcripts_CCDR_T0-output-v2-cdhitest --reference Oryza_sativa.IRGSP-1.0.cdna.all.fa
```

**Comment by blahah** [comment]
cc @cboursnell this is happening because bindeps installs to the `GEM_HOME` unless told otherwise or it can't find it: https://github.com/blahah/bindeps/blob/master/lib/bindeps.rb#L191.

We should either update the transrate wrapper bash script as above

**Comment by unalibun** [comment]
Hi everybody, I am having the same error : /Storage/data2/sandra.gonzalez/PacBio/annotation/braker_canu_softmasked/transcripts_pseudocercospora/transrate/transrate-1.0.3-linux-x86_64/lib/app/bin/transrate:13:in `raise': BLAST Error creating database (RuntimeError). That is quite weird because I am trying to evaluate several --reference and one of them finish the running successfully. I am running transrate executing the Linux binary, unpacking and adding the directory to my path. 

Here my script 

/Storage/data2/my_path/transrate/transrate-1.0.3-linux-x86_64/transrate --install-deps ref
/Storage/data2/my_path/transrate-1.0.3-linux-x86_64/transrate --threads 10 --assembly=/Storage/data2/my_path/p_u_polished.fasta --reference=/Storage/data2/My_path/PacBio/annotation/p_f_transcripts.fixed.fa --output=p_u_transcripts_f

Can anyone give me some advice? 

Best
