### ISSUE TITLE
Snap index error

### ISSUE THREAD

**Issue by asan-emirsaleh** [Blahah/transrate#248]
Hello!
Great tool. I have heard a lot about it before tried to use. I went by conda-way, just installing all dependencies described in recipe. But every attempt to run the transrate lead me to the error in the very basic stages of alignment metrics computing. I also noted that there are no programs found by `which` command of the shell, in report. Here I place the transrate output:
```
[DEPRECATION] The trollop gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
[ INFO] 2023-04-25 16:03:18 : Loading assembly: /project/asm/MeJa_rnaspades_def-k/PRJNA745038/transcripts.fasta
[ INFO] 2023-04-25 16:03:28 : Analysing assembly: /project/asm/MeJa_rnaspades_def-k/PRJNA745038/transcripts.fasta
[ INFO] 2023-04-25 16:03:28 : Results will be saved in /project/qc/MeJa_transrate/spades_K49-K73/transcripts
[DEBUG] 2023-04-25 16:03:28 : running command:
[DEBUG] 2023-04-25 16:03:28 : which snap-aligner
[DEBUG] 2023-04-25 16:03:28 : running command:
[DEBUG] 2023-04-25 16:03:28 : which salmon
[DEBUG] 2023-04-25 16:03:28 : running command:
[DEBUG] 2023-04-25 16:03:28 : which bam-read
[ INFO] 2023-04-25 16:03:28 : Calculating contig metrics...
[ INFO] 2023-04-25 16:03:43 : Contig metrics:
[ INFO] 2023-04-25 16:03:43 : -----------------------------------
[ INFO] 2023-04-25 16:03:43 : n seqs                       287895
[ INFO] 2023-04-25 16:03:43 : smallest                         73
[ INFO] 2023-04-25 16:03:43 : largest                       23622
[ INFO] 2023-04-25 16:03:43 : n bases                   290176352
[ INFO] 2023-04-25 16:03:43 : mean len                    1007.73
[ INFO] 2023-04-25 16:03:43 : n under 200                     369
[ INFO] 2023-04-25 16:03:43 : n over 1k                    105698
[ INFO] 2023-04-25 16:03:43 : n over 10k                       82
[ INFO] 2023-04-25 16:03:43 : n with orf                   100227
[ INFO] 2023-04-25 16:03:43 : mean orf percent               52.5
[ INFO] 2023-04-25 16:03:43 : n90                             387
[ INFO] 2023-04-25 16:03:43 : n70                            1063
[ INFO] 2023-04-25 16:03:43 : n50                            1634
[ INFO] 2023-04-25 16:03:43 : n30                            2309
[ INFO] 2023-04-25 16:03:43 : n10                            3753
[ INFO] 2023-04-25 16:03:43 : gc                             0.41
[ INFO] 2023-04-25 16:03:43 : bases n                       26148
[ INFO] 2023-04-25 16:03:43 : proportion n                    0.0
[ INFO] 2023-04-25 16:03:43 : Contig metrics done in 15 seconds
[ INFO] 2023-04-25 16:03:43 : Calculating read diagnostics...
[DEBUG] 2023-04-25 16:03:43 : running command:
[DEBUG] 2023-04-25 16:03:43 : /home/asan/miniconda3/envs/transrate-env/bin/snap-aligner index /project/asm/MeJa_rnaspades_def-k/PRJNA745038/transcripts.fasta transcripts -s 23 -t100 -bSpace -locationSize 4
[ERROR] 2023-04-25 16:03:49 : Failed to build Snap index
Welcome to SNAP version 1.0dev.96.

Saving genome...0s

[DEBUG] 2023-04-25 16:03:49 : /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/bin/transrate:13:in `raise' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/snap.rb:147:in `block in build_index' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/snap.rb:125:in `loop' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/snap.rb:125:in `build_index' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/read_metrics.rb:52:in `run' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/transrater.rb:98:in `read_metrics' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:506:in `read_metrics' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:402:in `block in analyse_assembly' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:398:in `chdir' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:398:in `analyse_assembly' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:38:in `block (2 levels) in run' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:37:in `zip' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:37:in `block in run' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:32:in `chdir' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/lib/transrate/cmdline.rb:32:in `run' /home/asan/miniconda3/envs/transrate-env/lib/ruby/gems/2.5.0/gems/transrate-1.0.3/bin/transrate:23:in `<top (required)>' /home/asan/miniconda3/envs/transrate-env/bin/transrate:23:in `load' /home/asan/miniconda3/envs/transrate-env/bin/transrate:23:in `<main>'
```
Are there any suggestion how to make it working? What does cause the problem? Do you plan to update Snap aligner version? Why the filds of running commands and which are blank?

Best regards
Asan

**Comment by bpenaud** [comment]
Hello,

I also install transrate with conda and I'm encountering the same error. Have you finally found a solution?

Best Regards,
Benjamin

**Comment by asan-emirsaleh** [comment]
Hello @bpenaud !
It did finally work for me. I have used a `transrate` binary bundled with the [Oyster River Protocol](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6078068/) pipeline. If I find additional details I will notify you.

Best regards
Asan

**Comment by doctor-patient** [comment]
Hello @asan-emirsaleh. I'm having the same problem. I'm using Windows Subsystem for Linux. How did you solve it?

**Comment by bslgrg00** [comment]
Hello everyone,
I am encountering the same issue. Has anyone been able to resolve this? Any insights would be greatly appreciated.

**Comment by dankunk** [comment]
Currently experiencing this same issue. My transcriptome assembly is large though (~80,000 seqs, not as much as @asan-emirsaleh 's example).

Is everyone else's assembly large as well? Could this be an issue with RAM/the defaults used for any Snap calls (i.e. default locationSize). Lots of these packages/versions are quite old and trying to get good documentation for these versions has been difficult.

**Comment by user-tq** [comment]
> Hello [@bpenaud](https://github.com/bpenaud) !  你好！ It did finally work for me. I have used a `transrate` binary bundled with the [Oyster River Protocol](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6078068/) pipeline. If I find additional details I will notify you.这招终于对我有效了。我用过一个与 [Oyster River 协议](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6078068/)流水线捆绑的`传输二`进制文件。如果我找到更多细节，我会通知你。
> 
> Best regards  此致敬礼 Asan  阿山

[中文原文]
Oyster River Protocol 这一项目将 transrate 的二进制文件及其依赖保存为 orp-transrate.tar.gz，因此它不需要通过 conda 安装，这或许是能避免问题的关键原因。 通过 orp 提供的 docker 镜像构建 apptainer 的镜像，在镜像中使用 transrate 是最快的方法。
```
apptainer build orp_2.3.3.sif docker://macmaneslab/orp:2.3.3
apptainer shell orp_2.3.3.sif
transrate -v
```
[English Translation]
The Oyster River Protocol project packages the transrate binary files and their dependencies into orp-transrate.tar.gz. Consequently, it does not require installation via conda, which is likely the key reason for avoiding potential issues. Building an Apptainer image using the Docker image provided by ORP is the fastest method to use transrate within the image.
```
apptainer build orp_2.3.3.sif docker://macmaneslab/orp:2.3.3
apptainer shell orp_2.3.3.sif
transrate -v
```
