### ISSUE TITLE
Transrate FASTQ based run not working

### ISSUE THREAD

**Issue by Gruxxis** [Blahah/transrate#251]
Hi,
I have installed transrate and I managed to run the assembly evaluation with no problems.
However, when I try to make a run including fastq files, i get this error:

```
[DEPRECATION] The trollop gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
/Library/Ruby/Gems/2.6.0/gems/transrate-1.0.1/bin/transrate:13:in `raise': bindeps config for snap doesn't contain an entry for 32bit (Bindeps::UnsupportedSystemError)
	from /Library/Ruby/Gems/2.6.0/gems/bindeps-1.2.1/lib/bindeps.rb:103:in `choose_url'
	from /Library/Ruby/Gems/2.6.0/gems/bindeps-1.2.1/lib/bindeps.rb:77:in `initialize'
	from /Library/Ruby/Gems/2.6.0/gems/bindeps-1.2.1/lib/bindeps.rb:47:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/bindeps-1.2.1/lib/bindeps.rb:47:in `block (3 levels) in missing'
	from /Library/Ruby/Gems/2.6.0/gems/bindeps-1.2.1/lib/bindeps.rb:44:in `each_pair'
	from /Library/Ruby/Gems/2.6.0/gems/bindeps-1.2.1/lib/bindeps.rb:44:in `block (2 levels) in missing'
	from /Library/Ruby/Gems/2.6.0/gems/bindeps-1.2.1/lib/bindeps.rb:43:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/bindeps-1.2.1/lib/bindeps.rb:43:in `block in missing'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /Library/Ruby/Gems/2.6.0/gems/bindeps-1.2.1/lib/bindeps.rb:42:in `missing'
	from /Library/Ruby/Gems/2.6.0/gems/transrate-1.0.1/lib/transrate/cmdline.rb:254:in `check_dependencies'
	from /Library/Ruby/Gems/2.6.0/gems/transrate-1.0.1/lib/transrate/cmdline.rb:163:in `check_arguments'
	from /Library/Ruby/Gems/2.6.0/gems/transrate-1.0.1/lib/transrate/cmdline.rb:17:in `initialize'
	from /Library/Ruby/Gems/2.6.0/gems/transrate-1.0.1/bin/transrate:22:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/transrate-1.0.1/bin/transrate:22:in `<top (required)>'
	from /usr/local/bin/transrate:23:in `load'
	from /usr/local/bin/transrate:23:in `<main>'
```
I also get the [DEPRECATION] warning when i ran the assembly evaluation from a fasta file, but that works nicely.

How can I solve this?

**Comment by jhb5696** [comment]
Hi, 

Have you found a solution to this problem? I got the exact same message when I tried to run the transrate now.
