### ISSUE TITLE
Bowtie alignment fails

### ISSUE THREAD

**Issue by MatthewRalston** [Blahah/transrate#55]
The standard functionality seems to be working fine (see below). 
1. (see 3rd command) When the left and right reads are supplied, (in this case it fails due to unpaired reads lumped in with the paired reads a la Trinity) no error is provided for the failure of bowtie. Including this output may help the user diagnose the problem with their reads through bowtie2's error report, as it's clear that this is not due to transrate.
2. Also, I noticed that there is no option for supplying unpaired reads to bowtie2. In my data set, close to half of my Trimmomatic processed read pairs resulted in unpaired reads so this could be a wonderful feature and very easy to implement. I wouldn't mind contributing to this. :)
3. (see 4th command) I've reached an error that I don't quite understand. Any ideas?
```
$ ls tranrate
total 2.2M
-rw-r--r-- 1 mrals class 1.2M Jul  9 10:13 CAC_proteins.fasta
-rw-r--r-- 1 mrals class 139K Jul  9 10:13 Trinity-GG.fasta
$ which bowtie2
/usr/local/bowtie2-2.1.0/bowtie2
$ transrate -a Trinity-GG.fasta --left ../tmp/left.fq --right ../tmp/right.fq -t 4
[ INFO]: Loading reference dataset
[ INFO]: Loading assembly: Trinity-GG.fasta
[ INFO]: Analysing assembly: Trinity-GG.fasta
[ INFO]: Calculating contig metrics...
[ INFO]: Contig metrics:
[ INFO]: -----------------------------------
[ INFO]: n seqs                          146
[ INFO]: smallest                        204
[ INFO]: largest                        5355
.
.
.
[ INFO]: at skew                        0.02
[ INFO]: cpg ratio                      0.47
[ INFO]: bases n                           0
[ INFO]: proportion n                    0.0
[ INFO]: linguistic complexity          0.16
[ INFO]: Contig metrics done in 0.4012817 seconds
[ INFO]: Calculating read diagnostics...
/home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/lib/transrate/read_metrics.rb:91:in `analyse_read_mappings': samfile /home/mrals/ETP/tranrate/left.fq.right.fq.Trinity-GG.sam not found (RuntimeError)
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/lib/transrate/read_metrics.rb:35:in `run'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/lib/transrate/transrater.rb:93:in `read_metrics'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/bin/transrate:157:in `block in <top (required)>'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/bin/transrate:123:in `each'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/bin/transrate:123:in `<top (required)>'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/bin/transrate:23:in `load'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/bin/transrate:23:in `<main>'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'
$ ls
total 19M
-rw-r--r-- 1 mrals class 1.2M Jul  9 10:13 CAC_proteins.fasta
-rw-r--r-- 1 mrals class    0 Jul  9 10:15 left.fq.right.fq.Trinity-GG.sam
-rw-r--r-- 1 mrals class  414 Jul  9 10:15 transrate.csv
-rw-r--r-- 1 mrals class 4.1M Jul  9 10:15 Trinity-GG.1.bt2
-rw-r--r-- 1 mrals class 260K Jul  9 10:15 Trinity-GG.2.bt2
-rw-r--r-- 1 mrals class 1.3K Jul  9 10:15 Trinity-GG.3.bt2
-rw-r--r-- 1 mrals class  33K Jul  9 10:15 Trinity-GG.4.bt2
-rw-r--r-- 1 mrals class 139K Jul  9 10:13 Trinity-GG.fasta
-rw-r--r-- 1 mrals class 4.1M Jul  9 10:15 Trinity-GG.rev.1.bt2
-rw-r--r-- 1 mrals class 260K Jul  9 10:15 Trinity-GG.rev.2.bt2
$ transrate -a Trinity-GG.fasta --left ../final/finalfastq/NS30A.fastq.1.gz --right ../final/finalfastq/NS30A.fastq.2.gz -t 4
[ INFO]: Loading reference dataset
[ INFO]: Loading assembly: Trinity-GG.fasta
[ INFO]: Analysing assembly: Trinity-GG.fasta
[ INFO]: Calculating contig metrics...
[ INFO]: Contig metrics:
[ INFO]: -----------------------------------
[ INFO]: n seqs                          146
[ INFO]: smallest                        204
[ INFO]: largest                        5355
.
.
.
[ INFO]: proportion n                    0.0
[ INFO]: linguistic complexity          0.16
[ INFO]: Contig metrics done in 0.3956906 seconds
[ INFO]: Calculating read diagnostics...
[ERROR]: reached the end of assembly enumerator while there were contigs left in the coverage results
[ERROR]: final assembly contig: GG30
[ERROR]: coverage contig: GG1|c0_g1_i1
/home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/lib/transrate/assembly.rb:217:in `next': iteration reached an end (StopIteration)
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/lib/transrate/assembly.rb:217:in `block in each_with_coverage'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/lib/transrate/assembly.rb:205:in `each_line'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/lib/transrate/assembly.rb:205:in `each_with_coverage'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/lib/transrate/read_metrics.rb:216:in `analyse_coverage'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/lib/transrate/read_metrics.rb:36:in `run'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/lib/transrate/transrater.rb:93:in `read_metrics'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/bin/transrate:157:in `block in <top (required)>'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/bin/transrate:123:in `each'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/gems/transrate-0.2.0/bin/transrate:123:in `<top (required)>'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/bin/transrate:23:in `load'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/bin/transrate:23:in `<main>'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
        from /home/mrals/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by Blahah** [comment]
All these issues have either been solved, or are now redundant as we have moved to SNAP
